### ISSUE TITLE
How to obtain token

### ISSUE THREAD

**Issue by ovs1** [dinizthiagobr/tinderino#1]
Is there a correct way to obtain the token? I tryed to sniff the api calls and took the X-Auth token but it did not work when i put it in the tool. Is there something more i need to do?

The token is from the headers from using ios tinder app.

Respons:

HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=utf-8
Date: Fri, 24 Mar 2017 16:51:25 GMT
X-Request-ID: ar04tdier6tphlo92glg
Content-Length: 25
Connection: keep-alive

{"status":401,"error":""}

**Comment by dinizthiagobr** [comment]
I used Fiddler to intercept the calls from my Android phone, but any other sniffer should work.
This code hasn't been update in a while, and I know the "Get Profiles" API call changed to "https://api.gotinder.com/recs/core", so maybe that's what you're missing.

Again, I suggest you use Fiddler to analyze the API calls, it is a great app.

**Comment by ovs1** [comment]
Yes, it's fiddler that i use it's sure great. I did not really look into the calls to be honest i should do that. But i saw there was an update few days ago on this git so i thought it was up to date my bad. Looks really nice will see if i can get it to work thank you! i hope you find motivation and time to update this in future great job!

**Comment by dinizthiagobr** [comment]
Good luck! Anything you can contact me.
